[project]
name = "zaparoo-label-automator"
version = "0.1.0"
description = "Automating creation of labels for zaparoo using IGDB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[tool.pylint.format]
max-line-length = 120
